# Generated by Django 5.1.15 on 2026-09-16 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25)),
                ('alert_type', models.CharField(choices=[('OVERDUE', 'Overdue Alert'), ('DUE_SOON', 'Due Date Reminder'), ('RETURN_RECEIPT', 'Return Acknowledgment'), ('CUSTOM', 'Custom Message')], default='DUE_SOON', max_length=20)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('BOTH', 'WhatsApp & SMS')], default='BOTH', max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='library.borrowrecord')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
